### ISSUE TITLE
How to access the Pegasus interface in TheSkyX on a Mac?

### ISSUE THREAD

**Issue by jamiesmith** [rpineau/PegasusUPB#1]
Hi- I am considering moving to a PegasusUPB from my Eagle3pro so I can drive my imaging from my Mac.  I ran the installer package for the x2 plugin but can't figure out how to access the settings for the UPB in TheSkyX pro.  

How/where in theskyx do I control the box?  

Thanks

**Comment by rpineau** [comment]
Go to the imaging setup, then settings -> more settings :
See this screenshot :
https://sbforum.s3.amazonaws.com/UPB%20settings%20access.png

**Comment by jamiesmith** [comment]
Glorious, thank you for the fast response.  Found it!
